
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# ===========================================
# Konfiguration für HA Struktur
# ===========================================

homeassistant:
  packages: !include_dir_named sensor_configs # (für separate YAML Dateien)

recorder:
  commit_interval: 60 # nur alle x Sekunden in Datenbank schreiben
  purge_keep_days: 7  # alte Daten löschen
  include:
    entity_globs:
      - sensor.*leistung*
      - sensor.*energie*
      - sensor.netz*
      - sensor.solis*
      - sensor.batt*
      - sensor.gas*
    entities:
      - sensor.home_power_production_now
      - sensor.hausverbrauch
      - sensor.wr_leistung
      - sensor.ha_datenbank_groesse
  exclude:
    entity_globs:
      - sensor.*raw*
      - device_tracker.*
      - sensor.shelly*

influxdb: # Aus HA Apps installiert - bessere Datenbank für zeitliche Abläufe 
  include:
    domains:
      - sensor
  exclude:
    # Hier werden spezielle Sensoren ausgewählt, die ignoriert werden
    # auch wenn sie oben durch ein Muster (Glob) erfasst wurden
    entity_globs:
      - sensor.*raw* # Schließt alle Sensoren aus, die "raw" im Namen haben
      - sensor.*_status # Schließt Status-Texte aus (Influx mag Zahlen lieber)

# nur krasse Sachen loggen
logger:
  default: warning
  logs:
    homeassistant.components.modbus: warning
    pymodbus.logging: warning

# ===========================================
# template sensor: Reload reicht
# platform: integration und utility_meter: in configuration.yaml - immer Neustart nötig
# ===========================================

# === Riemann-Summe - Helfer für Energieverbrauch (kann nicht als Package geladen werden) ===

sensor:
  - platform: integration
    source: sensor.wr_leistung
    name: "Solis WR Energie"
    unique_id: solis_wr_energy_integral
    unit_prefix: k
    round: 2
    method: left

utility_meter:
  solis_wr_energie_taeglich:
    source: sensor.solis_wr_energie
    name: "Solis WR Energie Täglich"
    unique_id: solis_wr_energy_daily
    cycle: daily
