template:
  - sensor:

#       Wechselrichter Temperatur

      - name: "Solis Wechselrichter Temperatur"
        unique_id: solis_wr_temperature
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        icon: mdi:thermometer
        state: "{{ states('sensor.solis_raw_wr_temperature') | float(0) }}"

#       verfügbare PV Leistung (Überschuss)

      - name: "PV Leistung netto"
        unique_id: solis_pv_power_netto
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        icon: mdi:solar-power
        state: >
          {% set dc = states('sensor.solis_raw_pv_dc_power') | float(0) %}
          {% set wr = states('sensor.wr_leistung_mit_glattung') | float(0) %}
          {% set haus = states('sensor.hausverbrauch') | float(0) %}
          {% set wb = states('sensor.ebox_smart_power_active_import') | float(0) %}
          {% set netto = (dc - wr - haus + (wb * 1000)) | float(0) %}
          
          {% if netto > 0 %}
            {{ netto | round(1) }}
          {% else %}
            0
          {% endif %}

#       verfügbarer PV Strom (Überschuss)
          
      - name: "PV Strom Überschuss"
        unique_id: pv_current_available
        unit_of_measurement: "A"
        device_class: current
        state_class: measurement
        icon: mdi:solar-power
        state: >
          {% set ueberschuss = states('sensor.solis_pv_leistung_netto') | float(0) %}
          {% set u_l1 = states('sensor.netzspannung_l1') | float(0) %}
          {% set u_l2 = states('sensor.netzspannung_l2') | float(0) %}
          {% set u_l3 = states('sensor.netzspannung_l3') | float(0) %}
          {% set u_avg = ((u_l1 + u_l2 + u_l3) / 3) | float(230) %}

          {% if u_avg > 0 %}
            {{ (ueberschuss / (3 * u_avg)) | round(1) }}
          {% else %}
            0
          {% endif %}

#       Errechnete Wechselrichter Leistung

      - name: "WR Leistung"
        unique_id: solis_inverter_power
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        icon: mdi:solar-power
        state: >
          {# 1. Die Basis-Daten holen #}
          {% set dc = states('sensor.solis_raw_pv_dc_power') | float(0) %}
          {% set ac = states('sensor.solis_raw_pv_ac_power') | float(0) %}
          {% set batt = states('sensor.solis_raw_batt_p') | float(0) %}
          {% set haus = states('sensor.solis_netzleistung_aktuell') | float(0) %}

          {# 2. Der Durchsatz (x): Wie viel Energie bewegt sich insgesamt? #}
          {% set x = [dc, ac, (batt | abs), haus] | max %}

          {# 3. Der aktuelle Fehlerwert: Was wollen wir prüfen? #}
          {% set current_val = ((dc + batt) - ac) | abs %}

          {# 4. Die dynamische Grenze (Threshold) berechnen #}
          {# Wir nutzen x, um zu bestimmen, wie viel Fehler bei dieser Last erlaubt ist #}
          {% set p_raw = (12000000 / ((x + 150) ** 2) + 6) %}
          {% set t_calc = (x * p_raw / 100) %}

          {# 5. Sicherheits-Boden von 180W gegen Modbus-Latenz #}
          {% set threshold = [t_calc, 180] | max %}

          {# 6. Die Entscheidung #}
          {% if current_val > threshold or current_val > 1000 %}
            {{ states('sensor.wr_leistung') | float(35) }}
          {% else %}
            {{ current_val | round(1) }}
          {% endif %}

#       Wechselrichter Wirkungsgrad

      - name: "Solis WR Wirkungsgrad"
        unique_id: solis_inverter_efficiency
        unit_of_measurement: "%"
        state_class: measurement
        icon: mdi:percent-outline
        state: >
          {% set dc = states('sensor.solis_raw_pv_dc_power') | float(0) %}
          {% set ac = states('sensor.solis_raw_pv_ac_power') | float(0) %}
          {% set batt = states('sensor.solis_raw_batt_p') | float(0) %}
          {% set haus = states('sensor.solis_netzleistung_aktuell') | float(0) %}
          {% set wr = states('sensor.wr_leistung_mit_glattung') | float(0) %}
          {% set x = [dc, ac, (batt | abs), haus] | max %}

          {% if x > 50 %}
            {% set wirkungsgrad = ((1 - (wr / (dc + batt))) * 100) %}
          {% else %}
            0
          {% endif %}

          {% if 0 <= wirkungsgrad <= 100 %}
            {{ wirkungsgrad | round(1) }}
          {% else %}
            0
          {% endif %}

sensor:

#   Wechselrichter Leistung - Glättung durch Mittelwerte

  - platform: statistics
    name: "WR Leistung mit Glättung"
    unique_id: solis_inverter_power_smoothed
    entity_id: sensor.wr_leistung
    state_characteristic: mean
    # Anzahl der zuletzt genutzten Daten für den Durchschnitt
    sampling_size: 3
    # maximale Lebensdauer von 30 Minuten,
    max_age:
      minutes: 30

#   Riemann-Summe - Helfer für Energieverbrauch

  - platform: integration
    source: sensor.wr_leistung_mit_glattung
    name: "Solis WR Energie"
    unique_id: solis_wr_energy_integral
    unit_prefix: k
    round: 2
    method: left
    max_sub_interval:
      minutes: 5

utility_meter:
  solis_wr_energie_taeglich:
    source: sensor.solis_wr_energie
    name: "Solis WR Energie Täglich"
    unique_id: solis_wr_energy_daily
    cycle: daily
    periodically_resetting: false
