template:
  - sensor:

#       verfügbarer PV Strom (Überschuss)

      - name: "PV Strom Überschuss"
        unique_id: pv_current_available
        unit_of_measurement: "A"
        device_class: current
        state_class: measurement
        icon: mdi:solar-power
        state: >
          {% set ueberschuss = states('sensor.pv_leistung_netto') | float(0) %}
          {% set u_l1 = states('sensor.netzspannung_l1_min') | float(230) %}
          {% set u_l2 = states('sensor.netzspannung_l2_min') | float(230) %}
          {% set u_l3 = states('sensor.netzspannung_l3_min') | float(230) %}
          {% set u_sum = u_l1 + u_l2 + u_l3 %}
          {% if u_sum > 0 %}
            {{ (ueberschuss / u_sum) | round(2) }}
          {% else %}
            0
          {% endif %}

#   Ladeenergie ins Auto (zusätzliche Kapazität in %)

  - trigger:
      - platform: state
        entity_id: sensor.ebox_smart_status_connector
      - platform: state
        entity_id: sensor.ebox_smart_energy_active_import_register
      - platform: homeassistant
        event: start
      - platform: event
        event_type: event_template_reloaded
    sensor:
      - name: "Bis jetzt geladen (SOC)"
        unique_id: car_session_charge_percentage
        unit_of_measurement: "%"
        device_class: battery
        state_class: measurement
        icon: mdi:battery-charging
        availability: >-
          {{ is_number(states('sensor.ebox_smart_energy_active_import_register')) }}
        state: >-
          {% set status = states('sensor.ebox_smart_status_connector') %}
          {% set reg = states('sensor.ebox_smart_energy_active_import_register') | float(0) %}

          {% set capacity = 77 %}
          {% set base = 0.26 %}
          {% set conv = 90 %}
          {% set was_hold = this.attributes.get('hold', false) if this is defined else false %}

          {% if status == 'Preparing' %}
            {% set hold = true %}
          {% elif reg < 0.2 %}
            {% set hold = false %}
          {% else %}
            {% set hold = was_hold %}
          {% endif %}
          {% if hold %}
            0
          {% elif reg > base %}
            {{ ((reg - base) / capacity * conv) | round(1) }}
          {% else %}
            0
          {% endif %}
        attributes:
          hold: >-
            {% set was_hold = this.attributes.get('hold', false) if this is defined else false %}
            {% set status = states('sensor.ebox_smart_status_connector') %}
            {% set reg = states('sensor.ebox_smart_energy_active_import_register') | float(0) %}
            {% if status == 'Preparing' %}
              true
            {% elif reg < 0.2 %}
              false
            {% else %}
              {{ was_hold }}
            {% endif %}

sensor:

#   PV Strom Überschuss - Glättung durch Mittelwerte

  - platform: statistics
    name: "PV Strom Überschuss gefiltert"
    unique_id: pv_current_availabe_filtered
    entity_id: sensor.pv_strom_uberschuss
    state_characteristic: median
    max_age:
      seconds: 50
    precision: 2
  
  - platform: statistics
    name: "PV Strom Überschuss mit Glättung"
    unique_id: pv_current_available_smoothed
    entity_id: sensor.pv_strom_uberschuss_gefiltert
    state_characteristic: mean
    max_age:
      seconds: 30
    precision: 1

input_number:
  ladegrenze:
    name: Ladegrenze
    unit_of_measurement: "%"
    icon: mdi:battery-charging-70
    initial: 30
    min: 0
    max: 100
    step: 1
    mode: slider

# Helfer für die Logbuch Einträge in der PV Überschussladen Automation

input_button:
  pv_uberschuss_log:
    name: "PV Überschuss Log"
    icon: mdi:format-list-bulleted-type

# Helfer für die Rundung des Ladestroms in der PV Überschussladen Automation

input_boolean:
  pv_runden_aufrunden:
    name: PV Überschuss – Rundungsmodus (on=ceil, off=floor)
    initial: false

timer:

# Timer für die "PV Überschussladen" Automation
# !!! KEINE VOLLEN MINUTEN SETZEN !!!
# um race condition mit Hauptsteuerung zu vermeiden

  ebox_sleep_protection:
    name: "eBox Sleep-Schutz Timer"
    duration: "00:04:30"
    icon: mdi:timer-outline

counter:

# Zähler für eBox Schaltvorgänge

  ebox_cc_einschaltvorgaenge:
    name: "eBox CC Einschaltvorgänge"
    initial: 0
    step: 1
    icon: mdi:toggle-switch

  ebox_cc_ausschaltvorgaenge:
    name: "eBox CC Ausschaltvorgänge"
    initial: 0
    step: 1
    icon: mdi:toggle-switch-off
